FROM python:3.11-slim

WORKDIR /app

COPY requirements_api.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py scaler.save best_model.h5 ./

EXPOSE 5000

CMD ["python", "app.py"]
